name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update system
      run: 
    - name: dependencies
      run: sudo apt update -qq
       sudo apt install -y libtool intltool autoconf automake libcurl4-openssl-dev pkg-config libglib2.0-dev libgtk-3-dev libgoocanvas-2.0-dev
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
